import { Analytics } from "@vercel/analytics/react";
import SupabaseProvider from "./_components/supabase-provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>{children}</SupabaseProvider>
        <Analytics />
      </body>
    </html>
  );
}
