import { Analytics } from "@vercel/analytics/react";
import { cookies, headers } from "next/headers";
import MobileDrawer from "./_components/MobileDrawer";
import SupabaseProvider from "./_components/supabase-provider";
import "./globals.css";
import { Drawer } from "./_components/Drawer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <MobileDrawer
            drawer={
              <>
                {/* @ts-expect-error Server Component */}
                <Drawer />
              </>
            }
          >
            {children}
          </MobileDrawer>
        </SupabaseProvider>
        <Analytics />
      </body>
    </html>
  );
}
